services:
  med-app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: med-app
    ports:
      - "8000:8000"
    environment:
      - API_URL=http://med-app:8000/predict
    env_file:
      - .env
    volumes:
      - ./creds:/creds:ro
    restart: unless-stopped

  med-frontend:
    build: ./frontend
    container_name: med-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://med-app:8000/predict
    depends_on:
      - med-app